stack/src/kernel/edrv/edrv-rawsock_linux.c: add missing <sys/types.h> include
This is necessary to get the definition of the u_char type, otherwise
the build fails with the musl C library with:

stack/src/kernel/edrv/edrv-rawsock_linux.c:373:46: error: ‘u_char’ undeclared (first use in this function)

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>