[FIX] Add findDebugfs() prototype
When FTRACE_DEBUG is defined for debugging purpose the build fails
with the following error:

ftracedebug.c:113:17: warning: implicit declaration of function
    'findDebugfs' [-Wimplicit-function-declaration]
    p_debugfs = findDebugfs();
ftracedebug.c:220:14: error: conflicting types for 'findDebugfs'
    static char* findDebugfs(void)

Add the findDebugfs() prototype at the top of the file.

Change-Id: I4856df669de3779d3d8dcb18252c944bc0890b48
Signed-off-by: Romain Naour <romain.naour@gmail.com>