[FIX] rename DEPRECATED to OPLK_DEPRECATED
DEPRECATED is already defined in include/linux/printk.h, so rename DEPRECATED introduced
by commit 9fe01285db96808bd7ee41db5905e6f241129bfa to OPLK_DEPRECATED.

Fixes:
openpowerlink-V2.3/drivers/linux/drv_kernelmod_edrv/../../../stack/include/oplk/targetsystem.h:161:0: warning: "DEPRECATED" redefined
 #define DEPRECATED      __attribute__((deprecated))
 ^
include/linux/printk.h:105:0: note: this is the location of the previous definition
 #define DEPRECATED "[Deprecated]: "
 ^

include/linux/printk.h:105:20: error: expected identifier or '(' before string constant
 #define DEPRECATED "[Deprecated]: "
                    ^
openpowerlink-V2.3/drivers/linux/drv_kernelmod_edrv/../../../stack/include/oplk/oplk.h:475:15: note: in expansion of macro 'DEPRECATED'
 OPLKDLLEXPORT DEPRECATED tOplkError oplk_init(tOplkApiInitParam* pInitParam_p);

Signed-off-by: Romain Naour <romain.naour@openwide.fr>