[FIX] add findDebugfs() prototype
When FTRACE_DEBUG is defined for debugging purpose the build fail with
the following error:

ftracedebug.c:113:17: warning: implicit declaration of function 'findDebugfs' [-Wimplicit-function-declaration]
     p_debugfs = findDebugfs();
ftracedebug.c:220:14: error: conflicting types for 'findDebugfs'
 static char* findDebugfs(void)

Add the findDebugfs() prototype at the top of the file.

Signed-off-by: Romain Naour <romain.naour@gmail.com>