edrv-rawsock_linux: add missing include for u_char type
Fixes:

edrv/edrv-rawsock_linux.c:373:46: error: 'u_char' undeclared (first use in this function)

http://autobuild.buildroot.org/results/63d/63d5b21b5581f2005d6ca2bd0558601cc17eaee1/build-end.log

Signed-off-by: Romain Naour <romain.naour@smile.fr>